steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build container image"
    args: ["build", "-t", "gcr.io/forecasting-347712/forecaster", "."]
    dir: "forecasting"
  - name: "gcr.io/cloud-builders/docker"
    id: "push container image to container registry"
    args: ["push", "gcr.io/forecasting-347712/forecaster"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy container image to cloud run"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "forecaster",
        "--image",
        "gcr.io/forecasting-347712/forecaster",
        "--region",
        "europe-west2",
        "--cpu",
        "4",
        "--memory",
        "4Gi",
        "--timeout",
        "3600",
        "--allow-unauthenticated",
        "--platform",
        "managed",
      ]
images:
  - gcr.io/forecasting-347712/forecaster
timeout: 3600s
