steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build container image"
    args: ["build", "-t", "gcr.io/test-rig-349313/anomaly-detection", "."]
    dir: "anomaly_detection"
  - name: "gcr.io/cloud-builders/docker"
    id: "push container image to container registry"
    args: ["push", "gcr.io/test-rig-349313/anomaly-detection"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "deploy container image to cloud run"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "anomaly-detection",
        "--image",
        "gcr.io/test-rig-349313/anomaly-detection",
        "--region",
        "europe-west2",
        "--cpu",
        "4",
        "--memory",
        "4Gi",
        "--timeout",
        "3600",
        "--allow-unauthenticated",
        "--platform",
        "managed",
        "--port", 
        "8080"
      ]
images:
  - gcr.io/test-rig-349313/anomaly-detection
timeout: 3600s
